import os

import joblib
from dotenv import load_dotenv

load_dotenv()
import streamlit as st

from src.preprocessing import clean_text
from src.interpretability import explain_single_prediction
from src.rag import explain_ham_stream, explain_spam_stream, load_spam_corpus, retrieve_similar_spam

SMS_MODEL_PATH = os.path.join("models", "sms_spam_model.joblib")
SMS_DATA_PATH = os.path.join("data", "sms_spam_collection.tsv")


@st.cache_resource
def load_model():
    return joblib.load(SMS_MODEL_PATH)


@st.cache_resource
def load_corpus(_pipeline):
    # underscore prefix tells Streamlit not to hash this arg
    return load_spam_corpus(SMS_DATA_PATH, _pipeline)


sms_model = load_model()
spam_texts, spam_vectors, vectorizer = load_corpus(sms_model)

st.title("SMS Spam Detector")
st.write(
    "This app predicts whether an SMS message is non-spam or spam. "
    "If spam is detected, a RAG agent will explain the red flags and how to "
    "protect yourself."
)

user_text = st.text_area("Paste your SMS message here")

if st.button("Check message"):
    if user_text.strip() == "":
        st.warning("Please paste a message first.")
    else:
        cleaned = clean_text(user_text)
        prediction = sms_model.predict([cleaned])[0]

        # the model labels are "ham"/"spam", but we display "Non-spam"/"Spam"
        if prediction == "spam":
            st.error("Prediction: Spam")
        else:
            st.success("Prediction: Non-spam")

        # Top model signals come straight from the TF-IDF + Linear SVM model:
        # for each feature in the message, contribution = tfidf value * SVM weight
        st.subheader("Top model signals")
        st.caption(
            "These signals come from the TF-IDF + Linear SVM model weights. "
            "Positive contributions push toward spam, negative toward non-spam."
        )
        signals = explain_single_prediction(sms_model, cleaned, top_n=8)
        if signals.empty:
            st.write("No strong known TF-IDF features were found for this message.")
        else:
            st.dataframe(signals)

        # The AI explanation below is separate from the SVM prediction:
        # it uses retrieved similar spam examples and an LLM
        similar = retrieve_similar_spam(
            user_text, spam_texts, spam_vectors, vectorizer, k=5
        )

        if prediction == "spam":
            st.subheader("AI explanation: why this is spam — and how to stay safe")
        else:
            st.subheader("AI explanation: why this message looks legitimate")
        st.caption(
            "This explanation is generated by a separate RAG/AI system, "
            "not by the SVM model itself."
        )

        if not os.environ.get("OPENROUTER_API_KEY"):
            st.warning(
                "Set the OPENROUTER_API_KEY environment variable to enable "
                "AI-powered explanations."
            )
        elif prediction == "spam":
            st.write_stream(explain_spam_stream(user_text, similar))
        else:
            st.write_stream(explain_ham_stream(user_text, similar))
